default:
  models:
    Notifications::Request: read
    Notifications::Flag: read
    Notification: read
    Retreats::Comment: read
    Organizations::Contact: read
    Items::Option: read
    Flights::Check: read
    Flights::Timeframe: read
    Flight: read
    Items::Tag: read
    Reservation: read
    Retreat: read
    Organization: read
    Item: read
    Location: read
    Department: read
    Demographic: read
    Team: read
    Membership:
      - read
      - search
    Platform::Application: read
    Webhooks::Outgoing::Endpoint: manage
    Webhooks::Outgoing::Event: read
    Webhooks::Outgoing::Delivery: read
    Webhooks::Outgoing::DeliveryAttempt: read
    Invitation:
      - read
      - create
      - destroy

editor:
  models:
    Scaffolding::CompletelyConcrete::TangibleThing: manage
    Scaffolding::AbsolutelyAbstract::CreativeConcept:
      - read
      - update

admin:
  includes:
    - editor
  manageable_roles:
    - admin
    - editor
  models:
    Notifications::Request: manage
    Notifications::Flag: manage
    Notification: manage
    Retreats::Comment: manage
    Organizations::Contact: manage
    Items::Option: manage
    Flights::Check: manage
    Flights::Timeframe: manage
    Flight: manage
    Items::Tag: manage
    Reservation: manage
    Retreat: manage
    Organization: manage
    Item: manage
    Location: manage
    Department: manage
    Demographic: manage
    Team: manage
    Membership: manage
    Scaffolding::AbsolutelyAbstract::CreativeConcept: manage
    Platform::Application: manage
