default:
  models:
    Retreats::Request: read
    Websiteimage: read
    Question: read
    Season: read
    Notifications::Request: read
    Notifications::Flag: read
    Notification: read
    Organizations::Contact: read
    Items::Option: read
    Flights::Check: read
    Flights::Timeframe: read
    Flight: read
    Items::Tag: read
    Reservation: read
    Retreat: read
    Organization: read
    Item: read
    Location: read
    Department: read
    Demographic: read
    Team: read
    Membership:
      - read
      - search
    Platform::Application: read
    Webhooks::Outgoing::Endpoint: manage
    Webhooks::Outgoing::Event: read
    Webhooks::Outgoing::Delivery: read
    Webhooks::Outgoing::DeliveryAttempt: read
    Invitation:
      - read
      - create
      - destroy

editor:
  models:
    Scaffolding::CompletelyConcrete::TangibleThing: manage
    Scaffolding::AbsolutelyAbstract::CreativeConcept:
      - read
      - update

host:
  includes:
    - default

planner:
  includes:
    - default
  models:
    Retreats::Comment: manage
    Retreat: manage
    Reservation: manage
    Season: manage
    Retreats::Request: manage
    

resource_editor:
  models:
    Items:
      - create
      - read
      - update
    Items::Option: manage
    Items::Tag: manage      

admin:
  includes:
    - editor
  manageable_roles:
    - admin
    - editor
    - planner
    - resource_editor
    - host
  models:
    Retreats::Request: manage
    Websiteimage: manage
    Question: manage
    Season: manage
    Notifications::Request: manage
    Notifications::Flag: manage
    Notification: manage
    Retreats::Comment: manage
    Organizations::Contact: manage
    Items::Option: manage
    Flights::Check: manage
    Flights::Timeframe: manage
    Flight: manage
    Items::Tag: manage
    Reservation: manage
    Retreat: manage
    Organization: manage
    Item: manage
    Location: manage
    Department: manage
    Demographic: manage
    Team: manage
    Membership: manage
    Scaffolding::AbsolutelyAbstract::CreativeConcept: manage
    Platform::Application: manage
