default:
  models:
    Organization: read
    Item: read
    Location: read
    Department: read
    Demographic: read
    Team: read
    Membership:
      - read
      - search
    Platform::Application: read
    Webhooks::Outgoing::Endpoint: manage
    Webhooks::Outgoing::Event: read
    Webhooks::Outgoing::Delivery: read
    Webhooks::Outgoing::DeliveryAttempt: read
    Invitation:
      - read
      - create
      - destroy

group_leader:
  includes:
    - default
  models:
    Retreat: read
    Reservation: manage
    Items: read
    Items::Option: read

default_staff:
  includes:
    - default
  models:
    Retreat: read
    Reservation: read
    Items: read
    Items::Option: read
    Notification: manage
    Notifications::Request: manage

managers:
  includes:
    - default
  models:
    Retreat: read
    Reservation: read
    Items: read
    Items::Option: read
    Flights::Check: read
    Notification: manage
    Notifications::Request: manage

host:
  includes:
    - group_leader

planner:
  includes:
    - group_leader
  models:
    Retreats::Comment: manage
    Retreat: manage
    Reservation: manage
    Season: manage
    Retreats::Request: manage
    Flights::Check: manage
    

resource_editor:
  models:
    Items:
      - create
      - read
      - update
    Items::Option: manage
    Items::Tag: manage   
    Flights::Check: manage
    Flights::Timeframe: manage
    Flight: manage  
    Notification: manage 

admin:
  includes:
    - editor
  manageable_roles:
    - admin
    - editor
    - planner
    - resource_editor
    - host
    - group_leader
    - default_staff
    
  models:
    Retreats::Request: manage
    Websiteimage: manage
    Question: manage
    Season: manage
    Notifications::Request: manage
    Notifications::Flag: manage
    Notification: manage
    Retreats::Comment: manage
    Organizations::Contact: manage
    Items::Option: manage
    Flights::Check: manage
    Flights::Timeframe: manage
    Flight: manage
    Items::Tag: manage
    Reservation: manage
    Retreat: manage
    Organization: manage
    Item: manage
    Location: manage
    Department: manage
    Demographic: manage
    Team: manage
    Membership: manage
    Scaffolding::AbsolutelyAbstract::CreativeConcept: manage
    Platform::Application: manage