json.extract! retreat,
  :id,
  :team_id,
  :name,
  :description,
  :arrival,
  :departure,
  :guest_count,
  :organization_id,
  :internal,
  :active,
  :jotform,
  :location_ids,
  :demographic_ids,
  :planner_ids,
  :host_ids,
  :contact_ids,
  :actual_group_size,
  :nps,
  :debrief,
  # 🚅 super scaffolding will insert new fields above this line.
  :created_at,
  :updated_at

# 🚅 super scaffolding will insert file-related logic above this line.
